### ISSUE TITLE
unable to add polyline to layers

### ISSUE THREAD

**Issue by chataign** [mozman/dxfwrite#1]
Hi, I am trying to write polylines into a DXF file using dxfwrite.

Polylines are read from DXF as LWPOLYLINE objects using dxfgrabber, and I want to export certain layers as DXF files.

I'm able to export INSERT entities using the following code:
```
dxf_insert = dxfwrite.DXFEngine.insert( insert.name, ( insert.pos.x(), insert.pos.y() ), layer=self.name )
drawing.add(dxf_insert)
```

But the following code for polylines doesnt seem to work:
```
vertices = [ ( pos.x(), pos.y() ) for pos in polyline.getVertices() ]
dxf_polyline = dxfwrite.DXFEngine.polyline( vertices, layer=self.name, linetype='DASHED', color=1)
drawing.add(dxf_polyline)
```

What am I doing wrong?
Kind regards,

**Comment by mozman** [comment]
How does it not work?

**Comment by chataign** [comment]
Apologies, I realized later that the polylines are added correctly but as entities with DXF type 'POLYLINE' instead of 'LWPOLYLINE' as existed in my original DXF file.
