### ISSUE TITLE
Created dxf is described as read only by AutoDesk

### ISSUE THREAD

**Issue by andrewkenny** [mozman/dxfwrite#3]
Thanks for a great package.

I noticed that the dxf generated is described as read only by autodesk when I open it.
I presume this is because either:

1. Intended behavior
2. A step is required after the save method to properly close the file.

Thanks for any advice you can give.

**Comment by mozman** [comment]
There is no read only mode for DXF files, I assume AutoCAD tries to open the DXF file in 2 instances and the 2nd instance has to use a read only mode. This happens if you launch AutoCAD by double clicking on the DXF file.
