### ISSUE TITLE
export shaped polylines

### ISSUE THREAD

**Issue by ddLeon28** [mozman/dxfwrite#4]
This is a closed polyline, I want to add to my drawing.
`drawing.add(dxf.polyline([(0,0,0),(20,0,0),(20,10,0)], flags=1))`

I want to export the inner part of polyline shaped like a rectangle. 
`drawing.add(dxf.rectangle((0,0,0), 2, 2, bgcolor=0))`

What should I do to make the polline shaped?

**Comment by mozman** [comment]
Sorry the POLYLINE entity has no fill property, use SOLID instead, but SOLID has max. 4 points, that is a limitation of the DXF R12 format, with [ezdxf](https://github.com/mozman/ezdxf) you can use later DXF versions which support the HATCH entity.

**Comment by ddLeon28** [comment]
Thank you. I will try it with ezdxf.
